print("Hello World\a");
print("Hello World\b");
print("Hello World\cx");
print("Hello World\C-x");
print("Hello World\e");
print("Hello World\f");
print("Hello World\M-\C-x");
print("Hello World\n");
print("Hello World\756");
print("Hello World\r");
print("Hello World\s");
print("Hello World\t");
print("Hello World\v");
print("Hello World\xab")
