print((lambda str="abc": str)())
print((lambda str="abc=%s":str%str)())
print((lambda str="abc=%s def%%def": str%str)())
print((lambda str="abc=%s def%%%%def": str%str%str)())
print((lambda str='print(lambda str=%s:str)()': str)())
print((lambda str='print(lambda str=%s:str)()': str%str)())
print((lambda str='print(lambda str=%s:str%str)()': str)())
print((lambda str='print(lambda str=%s:str%%str)()': str%str)())
print((lambda str='print(lambda str=%s:(str %% str))()': str % str)())
